### ISSUE TITLE
Criar modelos de Hardware

### ISSUE THREAD

**Issue by vinioliveira7** [LuanRoger/MegabyteStore#6]
Modelos:

- [x] Produto
- [x] Hardware
- [x] Placa-mãe
- [x] CPU
- [x] GPU
- [x] Fonte
- [x] Memoria ram
- [x] Armazenamento interno

**Comment by LuanRoger** [comment]
Atribuído a @vinioliveira7

**Comment by LuanRoger** [comment]
- Feito em #1
